# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', markdownx.models.MarkdownxField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
