# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161216_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfield', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2017, 3, 29, 16, 3, 36, 481611)),
        ),
    ]
