# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170329_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2017, 3, 29, 16, 8, 49, 286133)),
        ),
    ]
