# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170329_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2017, 4, 12, 20, 18, 55, 302000)),
        ),
    ]
